= Longan Nano v1.0
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Asciidoctor-link: https://asciidoctor.org[Asciidoctor]
:dfu-util: http://dfu-util.sourceforge.net/[dfu-util]
:Fedora: https://getfedora.org/[Fedora]
:Fedora-Silverblue: https://silverblue.fedoraproject.org/[Fedora Silverblue]
:fish: https://fishshell.com/[fish]
:Git: https://git-scm.com/[Git]
:Linux: https://www.linuxfoundation.org/[Linux]
:Longan-Nano-HAL: https://github.com/riscv-rust/longan-nano[Longan Nano HAL]
:Neopixel: https://learn.adafruit.com/adafruit-neopixel-uberguide[Neopixel]
:OpenOCD: https://openocd.org/[OpenOCD]
:RISC-V-OpenOCD-port: https://github.com/riscv/riscv-openocd[RISC-V OpenOCD port]
:Python: https://www.python.org/[Python]
:rustup: https://rustup.rs/[rustup]
:Rouge: https://rouge.jneen.net/[Rouge]
:Ruby: https://www.ruby-lang.org/en/[Ruby]
:Rust: https://www.rust-lang.org/[Rust]
:RV-Link: https://gitee.com/zoomdy/RV-LINK[RV-LINK]
:SiPEED-Longan-Nano: http://longan.sipeed.com/en/[SiPEED Longan Nano]
:SiPEED-RISC-V-Debugger: https://www.seeedstudio.com/Sipeed-USB-JTAG-TTL-RISC-V-Debugger-ST-Link-V2-STM8-STM32-Simulator-p-2910.html[SiPEED RISC-V Debugger]
:smart-leds: https://github.com/smart-leds-rs/smart-leds[smart-leds]
:soft-blink: https://en.wikipedia.org/wiki/Pulse-width_modulation#Soft-blinking_LED_indicator[soft blink]
:ws2812-spi-rs: https://github.com/smart-leds-rs/ws2812-spi-rs[ws2812-spi-rs]

Examples of lighting effects for the {SiPEED-Longan-Nano}.

// todo Document RV-LINK usage.
// todo Document OpenOCD usage with the SiPEED debugger.

== Setup

. First, clone the repository.
+
[source,sh]
----
git clone https://github.com/jwillikers/neopixel-soft-blink.git
----

. Change to the project's directory.
+
[source,sh]
----
cd smart-leds-fx/boards/longan-nano
----

// todo
https://github.com/sifive/freedom-tools/releases
. Install the GNU RISC-V toolchain.
+
----
----

. Install the Rust toolchain for the GD32VF103CBT6 microcontroller.
+
[source,sh]
----
rustup target add riscv32imac-unknown-none-elf
----

=== Cargo Embed

. Install required packages for {cargo-embed}.
+
[source,sh]
----
sudo dnf -y install libusbx-devel systemd-devel
----

. Install the `cargo-embed` utility.
+
[source,sh]
----
cargo install cargo-embed
----

. Install the required Udev rules.
+
[source,sh]
----
wget -LqO - https://probe.rs/files/99-probe-rs.rules | sudo tee /etc/udev/rules.d/99-probe-rs.rules
----

. Load the new rules.
+
[source,sh]
----
sudo udevadm control --reload
----

. Apply the new rules.
+
[source,sh]
----
sudo udevadm trigger
----

=== dfu-util

To flash the Longan Nano over a USB connection, install the {dfu-util} program.

[NOTE]
----
As things stand now, you may need to build the latest version from source for flashing to work properly.
----

DNF::
+
[source,sh]
----
sudo dnf -y install dfu-util
----

Source::

[source,sh]
----
git clone git://git.code.sf.net/p/dfu-util/dfu-util
----

[source,sh]
----
cd dfu-util
----

. Generate the configure script.
+
[source,sh]
----
./autogen.sh
----

. Configure.
I set the program to be installed under `~/.local` here, since `~/.local/bin` is already on my `PATH`.
+
[source,sh]
----
./configure --prefix=$HOME/.local
----

. Build and install `dfu-util`.
+
[source,sh]
----
make install
----

=== RISC-V objcopy

You will also need the RISC-V variant of `objcopy` built from source in order to convert the ELF executable to a binary file.
The binary file can then be flashed with `dfu-util`.

. Install the necessary dependencies.
+
[source,sh]
----
sudo dnf -y install bison-devel flex-devel texinfo
----

. Clone the RISC-V binutils project.
+
[source,sh]
----
git clone https://github.com/sifive/riscv-binutils-gdb.git
----

. Change into the project's directory.
+
[source,sh]
----
cd riscv-binutils-gdb
----

. Run the configure script.
+
[source,sh]
----
./configure --target=riscv64-unknown-elf --disable-werror --with-python=no --disable-gdb --disable-sim --disable-libdecnumber --disable-libreadline --with-expat=yes --with-mpc=no --with-mpfr=no --with-gmp=no
----

. Build.
+
[source,sh]
----
make
----

== Flash

The Longan Nano can be flashed with the {dfu-util} over the USB-C connection or with a debug probe.

=== dfu-util

The {dfu-util} tool can be used to flash the Longan Nano directly over the USB-C port.

. Build the example.
+
[source,sh]
----
cargo build --example rgbw-neopixel-stick-soft-blink
----

. Create a binary from the example's ELF file.
+
[source,sh]
----
objcopy -O binary target/riscv32imac-unknown-none-elf/debug/examples/rgbw-neopixel-stick-soft-blink firmware.bin
----

. Attach the Longan Nano's USB-C port to your computer.

. Put the Longan Nano in bootloader mode by holding the `BOOT0` button pressed while pressing and releasing the reset button.

. Now flash the `.bin` file onto the Longan Nano using the `dfu-util` program.
+
[source,sh]
----
sudo dfu-util -a 0 -s 0x08000000:leave -D firmware.bin
----

=== Cargo Embed

Debug probes can be used with cargo-embed to easily flash the Longan Nano.
The J-Link, {SiPEED-RISC-V-Debugger}, and {RV-LINK} are all supported.
With a debugger attached, just use {cargo-embed} to flash the desired example to the Longan Nano.

[source,sh]
----
cargo embed --example rgbw-neopixel-stick-soft-blink
----

== Debug

Debugging can be done using a J-Link, {SiPEED-RISC-V-Debugger}, or {RV-LINK}.

. First, attach the debug probe to the pins opposite the USB-C port of the Longan Nano.

. With a debug probe connected, start {OpenOCD} with the configuration for the appropriate probe as detailed below.
+
SiPEED RISC-V Debugger::
+
--
Use the `sipeed-jtag.cfg` for the {SiPEED-RISC-V-Debugger}.

[NOTE]
----
Currently, stock OpenOCD 0.11.0 doesn't work for me, so I have to use the {RISC-V-OpenOCD-port}.
There's also https://github.com/riscv-mcu/riscv-openocd[this fork] for RISC-V.
----

[source,sh]
----
openocd -f sipeed-jtag.cfg -f openocd.cfg
----
--

RV-LINK:: todo I haven't test this myself yet, but instructions for using the {RV-LINK} can be found https://github.com/riscv-rust/longan-nano#using-rv-link-for-flashing-and-debugging[here].

. Now, launch GDB using `cargo run` subcommand and the desired example.
+
[source,sh]
----
cargo run --example rgbw-neopixel-stick-soft-blink
----

== Examples

rgbw-neopixel-stick-soft-blink:: A _{soft-blink}_ effect for a stick of 8 RGBW {NeoPixel}s using the the SPI MOSI pin, pin A7, of the Longan Nano.

== Todo

* Improve power consumption by using sleep modes and disabling unused peripherals.

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* {Asciidoctor-link}
* {dfu-util}
* {Fedora}
* {Fedora-Silverblue}
* {fish}
* {Git}
* {Linux}
* {longan-nano-hal}
* {OpenOCD}
* {Python}
* {Rouge}
* {Ruby}
* {Rust}
* {smart-leds}
* {ws2812-spi-rs}

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is provided in the link:LICENSE.adoc[license file].

© 2021 Jordan Williams

== Authors

mailto:{email}[{author}]
