= Adafruit QT Py RP2040 Examples
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Adafruit-NeoPixel-LED-Strip-with-3-pin-JST-PH-Connector: https://www.adafruit.com/product/3919[Adafruit NeoPixel LED Strip with 3-pin JST PH Connector]
:Adafruit-QT-Py-RP2040: https://www.adafruit.com/product/4900[Adafruit QT Py RP2040]
:Asciidoctor-link: https://asciidoctor.org[Asciidoctor]
:elf2uf2-rs: https://github.com/JoNil/elf2uf2-rs[elf2uf2-rs]
:flip-link: https://github.com/knurling-rs/flip-link[flip-link]
:Git: https://git-scm.com/[Git]
:rp-hal: https://github.com/rp-rs/rp-hal[rp-hal]
:Rust: https://www.rust-lang.org/[Rust]
:rustup: https://rustup.rs/[rustup]
:smart-leds: https://github.com/smart-leds-rs/smart-leds[smart-leds]
:soft-blink: https://en.wikipedia.org/wiki/Pulse-width_modulation#Soft-blinking_LED_indicator[soft blink]
:UF2: https://github.com/microsoft/uf2[UF2]

Examples of lighting effects for the {Adafruit-QT-Py-RP2040}.

== Setup

. First, clone the repository.
+
[,sh]
----
git clone https://github.com/jwillikers/smart-leds-fx.git
----

. Change to the board's directory.
+
[,sh]
----
cd smart-leds-fx/boards/qt_py_rp2040
----

. Install the {Rust} toolchain for the Adafruit QT Py RP2040.
+
[,sh]
----
rustup target add thumbv6m-none-eabi
----

. Install {flip-link}
+
[,sh]
----
cargo install flip-link
----

== Program

The Adafruit QT Py RP2040 can be programmed directly through its micro USB port.
{elf2uf2-rs} makes it incredibly easy to flash the Adafruit QT Py RP2040 using its micro USB port.

. Install the `elf2uf2-rs` crate.
+
[,sh]
----
cargo install elf2uf2-rs
----

. While holding the `BOOTSEL` button, attach the Adafruit QT Py RP2040 to your computer using the micro USB port.

. Flash the board using Cargo's `run` subcommand.
+
[,sh]
----
cargo run --example rgb-neopixel-strand-high-low-soft-blink
----

== Examples

rgb-neopixel-strand-high-low-soft-blink:: A _{soft-blink}_ effect for an {Adafruit-NeoPixel-LED-Strip-with-3-pin-JST-PH-Connector} containing 30 RGB {NeoPixel}s using the SPI MOSI pin, GPIO 26, of the Adafruit QT Py RP2040.

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:../../CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* {Asciidoctor-link}
* {elf2uf2-rs}
* {flip-link}
* {Git}
* {probe-rs}
* {rp-hal}
* {Rust}
* {smart-leds}

== Code of Conduct

Refer to the project's link:../../CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

Licensed under either of

* Apache License, Version 2.0 (link:../../LICENSE-APACHE[LICENSE-APACHE] or http://www.apache.org/licenses/LICENSE-2.0)
* MIT license (link:../../LICENSE-MIT[LICENSE-MIT] or http://opensource.org/licenses/MIT)

at your option.

© 2022 Jordan Williams

== Authors

mailto:{email}[{author}]

